### ISSUE TITLE
BUG: Division

### ISSUE THREAD

**Issue by wehddn** [AdamWhiteHat/MultivariatePolynomial#1]
**Description**
Dividing a polynomial by a number does not work

**Error/Exception Message**
When I try to divide a polynomial by a number, I get 0. For example, 2*a / 2.
I created a polynomial for represent "2*a":
ind1 = new Indeterminate[] { new Indeterminate('a', 1) };
Term[] terms = new Term[] { new Term(2, ind1) };
MultivariatePolynomial pol = new MultivariatePolynomial(terms);

And the other for "2":
ind2 = new Indeterminate[0];
Term[] terms2 = new Term[] { new Term(2, ind2) };
MultivariatePolynomial pol2 = new MultivariatePolynomial(terms2);

And result of MultivariatePolynomial.Divide(pol, pol2) is 0;
At the same time, "(2*a)/(2*a)" or "(2*a)/2" works.
![Pol1](https://user-images.githubusercontent.com/22870381/218268577-4c24778b-9203-4e2b-929a-54459a44e12d.png)
![pol2](https://user-images.githubusercontent.com/22870381/218268579-3f39e271-4cf1-4242-bafb-7f6682141b9e.png)

**Comment by AdamWhiteHat** [comment]
@wehddn Thank you for bringing this to my attention.
[Commit 1b58331](https://github.com/AdamWhiteHat/MultivariatePolynomial/commit/1b58331037778ae78e06335d51efa2154cae8434) should fix this bug.

Care to pull the latest from the master branch, clean, rebuild and confirm that division now returns the correct result for you?

**Comment by AdamWhiteHat** [comment]
Cool. So I'm going to go ahead and close this issue now.

This should be working. I had taken your code as above [and placed it into a test](https://github.com/AdamWhiteHat/MultivariatePolynomial/blob/1b58331037778ae78e06335d51efa2154cae8434/TestMultivariatePolynomial/Arithmetic.cs#L272) that was included [in the above commit](https://github.com/AdamWhiteHat/MultivariatePolynomial/commit/1b58331037778ae78e06335d51efa2154cae8434), and it is passing now.

Thanks again for bringing this to my attention.

If you encounter any other issues or find anymore undesired behaviors, feel free to open another issue.
